name = "Network Addon Mod"
license = "MIT"
licenselink = "https://github.com/NAMTeam/namteam.github.io/blob/master/LICENSE"
description = "The official home of the Network Addon Mod documentation."

homepage = "https://github.com/NAMTeam"

[author]
  name = "Network Addon Mod Team"
  homepage = "https://github.com/NAMTeam"
